### ISSUE TITLE
Participant feedback during course

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/spatial-workshops#27]
It would be useful for folks to be able to give feedback during the sessions. 

From [Software Carpentry](http://software-carpentry.org/workshops/operations.html):

*Feedback, or "What Are the Sticky Notes For?"*

  * *During demonstrations, learners post a red sticky note on their laptop to indicate that they have a question or need help.*
  * *During exercises, learners post a red sticky note at the start of the exercise and switch to a green one when they finish, so the instructor can clearly see when everyone is ready to continue, and helpers can see who needs support.*
  * *Just before each break, the instructor will ask learners to write down one good point (something they learned or enjoyed) on their green sticky and one bad one (something that they still don't understand or that is bothering them) on their red sticky. It only takes a couple of minutes for the instructors to sort through these, and it tells them whether they're going too fast or too slow, what they need to review after the break, etc. (If possible, someone will mail the sticky notes to Software Carpentry admin after the workshop so we can look for patterns.)*

*At the very end of the workshop, the host or lead instructor can ask learners to give one good point or one bad one about the entire workshop. This can be done on the sticky notes, the Etherpad, or through a Google form. (This feedback will also be sent to Software Carpentry admin.)*

[More info on this in practice](https://dynamicecology.wordpress.com/2015/01/13/sticky-notes-as-a-teaching-and-lab-meeting-tool/).

Though I don't think we necessarily want to adopt the first point (as I don't think we have enough instructors to wander around and do this) I think the last point is a great idea. Doing this either via sticky notes or Etherpad seems like a useful idea. Stick notes are low-tech and don't require everyone to have a laptop or tablet, so I'm inclined to do that.

**Comment by dill** [comment]
What is this for? Make sure that folks know this is not the only way to give feedback and ask questions. Extra topics to cover?

Doesn't replace asking questions during the lecture!

**Comment by dill** [comment]
via the CIRCA folks at St Andrews [this SC thread](http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2015-October/thread.html#3376) talks about replacements for Mozilla's etherpad. [This](https://public.etherpad-mozilla.org/) seems like the obvious candidate.

**Comment by dill** [comment]
I've tried to cover this a little in https://github.com/DistanceDevelopment/spatial-workshops/blob/master/slides/1-welcome-landscape.pdf as of cda159b. We can flesh this out while we're talking too.

**Comment by jjrob** [comment]
Looks good.
