### ISSUE TITLE
Need to load segments in 3-simple-dsms.Rmd; also reload sightings

### ISSUE THREAD

**Issue by jjrob** [DistanceDevelopment/spatial-workshops#34]
When https://github.com/DistanceDevelopment/spatial-workshops/blob/master/exercises/3-simple-dsms.Rmd is run, the afternoon of the second day, this will be the first time that segments will exist. We will have created them in the morning of the second day.

`3-simple-dsms.Rmd` should be adjusted to:

* Load the segments, rather than relying on the earlier scripts (1 and 2) to have done it. Those earlier scripts cannot do it because the sightings did not exist yet (see #32, #33).

* Reload the sightings. They will now have a `SegmentID` field, that they did not have on the first day of class. We will have created and populated it in the morning of the second day (see #32 and #33 again).

**Comment by dill** [comment]
So I covered this a bit in my response to #33. I'll hold off on this until you look at that.

**Comment by dill** [comment]
Copying the previously fitted `df-models.RData` into the `Exercise_Day2.zip` directory, then running `process-geodata.Rmd` lets `2-simple-dsms.Rmd` run with no issues.
