### ISSUE TITLE
Add biographical details

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/spatial-workshops#37]
https://github.com/DistanceDevelopment/spatial-workshops/blob/master/slides/1-welcome-landscape.pdf (or rather https://github.com/DistanceDevelopment/spatial-workshops/blob/master/slides/1-welcome-landscape.Rpres) currently doesn't have biographical details for @jjrob.

**Comment by jjrob** [comment]
Updated my bio bullets

**Comment by dill** [comment]
Updated pdf and html files 6090463.
