### ISSUE TITLE
Exit questions

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/spatial-workshops#39]
We'd like to know how well we did at the end of the course. At St Andrews, the following questions are asked at the end of the workshop. I have made some modifications to make them appropriate to our course. What do you think?

1. If you attended the workshop with specific questions in mind, do you feel that your questions were answered?
2. Were your objectives in attend the workshop met? If not, where did we fail?
3. What lecture in this workshop was the most clear, which was the least clear?
4. How would you make the lectures and exercises more clear?
5. What improvements to the workshop would you suggest?
6. Was the amount of content in the workshop a) about right b) too little c) too much ?
7. We would appreciate your specific comment on the utility of the following (i.e. should we increase/decrease/continue this content or do something completely different)?
  - distance sampling detection functions
  - Horvitz-Thompson estimation of abundance
  - GAM "theory"
  - Model selection for DSMs
  - Predictions
  - Variance estimation for DSMs
  - Obtaining covariates
  - Plotting in R
  - Plotting in GIS
  - Preparing segment data in GIS
  - Preparing prediction data in GIS
  - "Advanced" material
  - Special topics

I suggest we have folks fill these out on paper during the course to maximise number of responses.

@jjrob can you add to 7. ?

**Comment by jjrob** [comment]
For 7 I suggest the following bullets:

7. We would appreciate your specific comment on the utility of the following (i.e. should we increase/decrease/continue this content or do something completely different)?
  - distance sampling detection functions
  - Horvitz-Thompson estimation of abundance
  - GAM "theory"
  - Model selection for DSMs
  - Predictions
  - Variance estimation for DSMs
  - Obtaining covariates
  - Plotting in R
  - Importing sightings from CSV files into ArcGIS
  - Importing tracklines from CSV files into ArcGIS and creating segments
  - Creating covariate rasters
  - Obtaining covariate values for survey segments
  - Making maps / data exploration in ArcGIS
  - "Advanced" material
  - Special topics

**Comment by dill** [comment]
We can incorporate this with the DEL survey so as to not overwhelm participants with requests for answers.

**Comment by dill** [comment]
Done.
