### ISSUE TITLE
Variance estimation problems negbin and varprop

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/spatial-workshops#43]
This is worrying.  Appears a `varprop` [issue was left unresolved](https://github.com/DistanceDevelopment/dsm/issues/29) at the beginning of April.  Hence, models with negbin distributions produce absurd (I hope they are absurd) variance estimates

#### Results produced on 21June
```
Summary of uncertainty in a density surface model calculated
 by variance propagation.

Quantiles of differences between fitted model and variance model
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
-1.31031 -0.04789  0.17085  0.01322  0.23876  0.27258 

Approximate asymptotic confidence interval:
        2.5%         Mean        97.5% 
    29.57459   2015.81785 137399.06890 
(Using log-Normal approximation)

Point estimate                 : 2015.818 
Standard error                 : 20412.4 
Coefficient of variation       : 10.1261 
```

#### Results from same fitted model lifted from Duke workshop notes
```
summary(var_nb_xy_ms)

## Summary of uncertainty in a density surface model calculated
##  by variance propagation.
## 
## Quantiles of differences between fitted model and variance model
##       Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
## -5.596e-06 -1.399e-07 -2.096e-08  1.690e-07  1.982e-07  7.159e-06 
## 
## Approximate asymptotic confidence interval:
##     2.5%     Mean    97.5% 
## 1005.079 1589.217 2512.848 
## (Using log-Normal approximation)
## 
## Point estimate                 : 1589.217 
## Standard error                 : 328.2824 
## Coefficient of variation       : 0.2066
```

### Threat from old 27March issue `disable var.prop() for negbin models`

* don't know if that action was taken
* whether taken or not, should practical be re-written so that negbin is not fit?

**Comment by dill** [comment]
I think this will require some maths to fix up (based on discussion with
MVB).

I recommend for now we don't allow varprop+nb in Distance UI. I will
look into whether we can do this in R once I am able to fix up the
maths...

**Comment by dill** [comment]
Solved in `dsm` repo.
