### ISSUE TITLE
Topics for 27 June teleco (DLM/ER)

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/spatial-workshops#44]
@dill so I can remember these at 0700 tomorrow morning

* workshop schedule still a bit fluid, but see preamble to practical notes for my best guess, at least about practicals
* should "missing" practical (data manipulation) be included in practical notes?
* bookdown version of practical document on Github [here](https://github.com/DistanceDevelopment/spatial-workshops/tree/master/exercises/bookdown)
    * modularised such that there is one .Rmd file per practical (except data manipulation prac)
* WTF to do with varprop and nb()
    * should we keep nb() estimation and prediction, but switch variance to var.gam?
    * I've prepared nothing for D7 portions of exercises awaiting decisions about this item
    * I'll down workshop tools around 5 July for 10 days to see Yellowknife
* who is sending R packages to CRAN?  will anything change in them before sending?
* test version of 3.4.1 is available now
* slight funkiness with latex math in kable() content *low importance*
* (non sequiter) distancesampling.org bibliography search continuously slow/broken (bad script)

**Comment by LHMarshall** [comment]
I'll send packages to CRAN... @dill you good to run tests on them? 
I'll use win builder to check them again.

**Comment by dill** [comment]
- workshop schedule still a bit fluid, but see preamble to practical notes for my best guess, at least about practicals
  - Len/Laura happy with Jan schedule proposal (see [https://github.com/DistanceDevelopment/spatial-workshops/issues/42](https://github.com/DistanceDevelopment/spatial-workshops/issues/42))
- should "missing" practical (data manipulation) be included in practical notes?
  - goes into bookdown, note to participants that they don't need it in workshops
- bookdown version of practical document on Github here
  - this looks good!
- WTF to do with varprop and nb()
  - see issue 29   
- who is sending R packages to CRAN? will anything change in them before sending?
  - Laura happy submitting, Dave needs to send to Laura -- @LHMarshall when do you want to do this?
- test version of 3.4.1 is available now
  - see above -- need to wait until R 3.4.1 released to submit?
- slight funkiness with latex math in `kable()` content low importance
  - maybe monkey with `output = "latex"` argument
- (non sequiter) `distancesampling.org` bibliography search continuously slow/broken (bad script)
  - Eric to e-mail Mark Schenck, the author. Replace jabref in the future? Remove search bar?

**Comment by dill** [comment]
I've now run devtools::check() on mrds, Distance and dsm latest github
versions. Seem to be passing.

cheers,
--dave

**Comment by LHMarshall** [comment]
is that in 3.4.1? can you also run devtools::build_win() when you are happy they are ready for release and I'll let you know how they go.

Cheers!

**Comment by dill** [comment]
only 3.4.0 as I don't see a 3.4.1 binary available for Mac yet. I will
do build_win() anyway.

**Comment by dill** [comment]
er, apparently I cannot do this...

Error in curl::curl_fetch_memory(url, handle = h) : Timeout was reached

I guess I'll have to do it manually...

**Comment by dill** [comment]
done, all e-mails should go to lhm@st-and...

**Comment by LHMarshall** [comment]
Distance looks [good](https://win-builder.r-project.org/RK4qifILhxEc/)
DSM [passes](https://win-builder.r-project.org/V54rPI1d5yMs/) without comment
