### ISSUE TITLE
arcGIS demonstration on podium computer?

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/spatial-workshops#49]
Showing what `Analysis.gdb` looks like.

**Comment by dill** [comment]
Phil says that this should work via the remote access from the university, we can check 18/7.

**Comment by erex** [comment]
yep, this is ArcMap running under "AppsAnywhere" on my desktop (AppsAnywhere requires another install) and serves ArcMap slowly, but adequately
![image](https://user-images.githubusercontent.com/330744/28320791-67fa55c0-6bc9-11e7-827b-c4f6a7723296.png)

**Comment by dill** [comment]
Great! Let's double check tomorrow too.

**Comment by erex** [comment]
better, QGIS can open gdb files as well
![image](https://user-images.githubusercontent.com/330744/28321373-011e81bc-6bcb-11e7-9db7-60b41312ad00.png)

**Comment by dill** [comment]
Ah it appears all I needed to earlier was drag and drop! Great! Let's do 
that instead.
