### ISSUE TITLE
package dependencies

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/spatial-workshops#51]
As before need a `install.packages()` line for folks to paste

**Comment by dill** [comment]
This needs to be tested on a fresh install machine to ensure that everything works. Ideally (and I realise this is tedious) without using `bookdown`.

**Comment by erex** [comment]
Spent the past hour in the computer lab.  I can confirm that Practical 5 (processing data) performs fine (rmd chunks execute individually and html file created) on two "fresh" machines (under R 3.3.3) after performing the package installation suggested on the landing webpage.
