### ISSUE TITLE
Introduction to the sperm whale data

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/spatial-workshops#52]
Are we going to fit detection functions to the sperm whale data?

Wherever we start talking about it we need to ensure that we give some background. I have that info but not sure where to put it.

**Comment by erex** [comment]
of course detection functions are going to be fitted [exercise 6](https://github.com/DistanceDevelopment/spatial-workshops/blob/master/exercises/bookdown/06-detection-functions.Rmd) does so

Monday morning (LJT) is going to have some form of detection function fitting

**Comment by dill** [comment]
Right, so the question is now whether @lenthomas will fit the spermwhale detection functions in his lectures/practicals or if that needs to go into the DSM material...

**Comment by erex** [comment]
Best approach is to leave detection function modelling of sperm whales inside the practical 6.  I suspect little attention needs be spent to lecturing about detection functions.   I would like to believe participants would be up to speed about detection function modelling courtesy of background reading they are asked to do (for intermediate workshop) along with detection function exposure they receive on Monday of workshop.

**Comment by dill** [comment]
Resolved.
